// <auto-generated />
using System;
using LeaveSystem.Db;
using LeaveSystem.Db.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeaveSystem.Migrations
{
    [DbContext(typeof(LeaveSystemDbContext))]
    [Migration("20220621152226_CreateUserLeaveLimit")]
    partial class CreateUserLeaveLimit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeaveSystem.Db.Domains.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<FederatedUser[]>("Users")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("LeaveSystem.Db.Domains.LeaveType", b =>
                {
                    b.Property<Guid>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseLeaveTypeId")
                        .HasColumnType("uuid");

                    b.Property<LeaveType.LeaveTypeProperties>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeaveTypeId");

                    b.HasIndex("BaseLeaveTypeId");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("LeaveSystem.Db.Domains.UserLeaveLimit", b =>
                {
                    b.Property<Guid>("UserLeaveLimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeaveTypeId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Limit")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("OverdueLimit")
                        .HasColumnType("interval");

                    b.Property<UserLeaveLimit.UserLeaveLimitProperties>("Property")
                        .HasColumnType("jsonb");

                    b.Property<FederatedUser>("User")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ValidSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserLeaveLimitId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("UserLeaveLimits");
                });

            modelBuilder.Entity("LeaveSystem.Db.Domains.LeaveType", b =>
                {
                    b.HasOne("LeaveSystem.Db.Domains.LeaveType", "BaseLeaveType")
                        .WithMany("ConstraintedLeaveTypes")
                        .HasForeignKey("BaseLeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseLeaveType");
                });

            modelBuilder.Entity("LeaveSystem.Db.Domains.UserLeaveLimit", b =>
                {
                    b.HasOne("LeaveSystem.Db.Domains.LeaveType", "LeaveType")
                        .WithMany("UserLeaveLimits")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveSystem.Db.Domains.LeaveType", b =>
                {
                    b.Navigation("ConstraintedLeaveTypes");

                    b.Navigation("UserLeaveLimits");
                });
#pragma warning restore 612, 618
        }
    }
}
