# @import ./login.http

###
# @name Get User Leave Limits
# @ref Login
# @reject-unauthorized
GET {{baseUrl}}/leavelimits/user?year=2024
X-Authorization: Bearer {{bearerToken}}
?? status == 200

###
# @name Get Leave Limits
# @ref Login
# @reject-unauthorized
GET {{baseUrl}}/leavelimits?year=2024&pagesize=1
X-Authorization: Bearer {{bearerToken}}
?? status == 200

###
# @name Get Leave Limit
# @ref Login
# @reject-unauthorized
GET {{baseUrl}}/leavelimits/ae6cdc66-dbc4-4307-b09b-e0be50f955b7
X-Authorization: Bearer {{bearerToken}}
?? status == 200

###
# @name Create Leave Limit
# @ref Login
# @reject-unauthorized
POST {{baseUrl}}/leavelimits
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 201
{}

###
# @name Update Leave Limit
# @ref Login
# @reject-unauthorized
PUT {{baseUrl}}/leavelimits/ae6cdc66-dbc4-4307-b09b-e0be50f955b7
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 200
{}

###
# @name Delete Leave Limit
# @ref Login
# @reject-unauthorized
DELETE {{baseUrl}}/leavelimits/ae6cdc66-dbc4-4307-b09b-e0be50f955b7
X-Authorization: Bearer {{bearerToken}}
?? status == 204