# @import ./login.http

###
# @name Get Leave Types
# @ref Login
# @reject-unauthorized
GET {{baseUrl}}/leavetypes
X-Authorization: Bearer {{bearerToken}}
?? status == 200

###
# @name Get Leave Type
# @ref Login
# @reject-unauthorized
GET {{baseUrl}}/leavetypes/6e1a75ca-07dc-45aa-9451-57e1cefd7ee6
X-Authorization: Bearer {{bearerToken}}
?? status == 200

###
# @name Create Leave Type
# @ref Login
# @reject-unauthorized
POST {{baseUrl}}/leavetypes
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 201
{}

###
# @name Update Leave Type
# @ref Login
# @reject-unauthorized
PUT {{baseUrl}}/leavetypes/ae6cdc66-dbc4-4307-b09b-e0be50f955b7
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 200
{}

###
# @name Delete Leave Type
# @ref Login
# @reject-unauthorized
DELETE {{baseUrl}}/leavetypes/ae6cdc66-dbc4-4307-b09b-e0be50f955b7
X-Authorization: Bearer {{bearerToken}}
?? status == 204