# @import ./secrets.http

###
# @name Search Leave Requests
# @reject-unauthorized
GET {{baseUrl}}/leaverequest?PageNumber=1
X-Authorization: Bearer {{bearerToken}}
?? status == 200

###
# @name Get Leave Request
# @reject-unauthorized
GET {{baseUrl}}/leaverequests/ae6cdc66-dbc4-4307-b09b-e0be50f955b7
X-Authorization: Bearer {{bearerToken}}
?? status == 200

###
# @name Create Leave Request
# @reject-unauthorized
POST {{baseUrl}}/leaverequests
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 201
{}

###
# @name Create Leave Request on behalf
# @reject-unauthorized
POST {{baseUrl}}/leaverequests/onbehalf
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 201
{}

###
# @name Accept Leave Request
# @reject-unauthorized
PUT {{baseUrl}}/leaverequests/ae6cdc66-dbc4-4307-b09b-e0be50f955b7/accept
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 200
{}

###
# @name Reject Leave Request
# @reject-unauthorized
PUT {{baseUrl}}/leaverequests/ae6cdc66-dbc4-4307-b09b-e0be50f955b7/reject
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 200
{}

###
# @name Cancel Leave Request
# @reject-unauthorized
PUT {{baseUrl}}/leaverequests/ae6cdc66-dbc4-4307-b09b-e0be50f955b7/cancel
Content-Type: application/json
X-Authorization: Bearer {{bearerToken}}
?? status == 200
{}