# Docs https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0
# Base repo https://github.com/SteveSandersonMS/BlazorOnGitHubPages/tree/master

name: Build and deploy Blazor .NET app to GitHub Pages

# Controls when the action will run
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install wasm-tools
        run: dotnet workload install wasm-tools

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: dotnet publish
        run: dotnet publish ./src/LeaveSystem.Web/LeaveSystem.Web/LeaveSystem.Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/LeaveSystem

      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{env.DOTNET_ROOT}}/LeaveSystem/bin/Release/net8.0/publish/wwwroot/index.html
          base_href: /leave-system/

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{env.DOTNET_ROOT}}/LeaveSystem/bin/Release/net8.0/publish/wwwroot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
