# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: LeaveSystem - Restore dependencies
      run: dotnet restore ./src/LeaveSystem/LeaveSystem.UnitTests/LeaveSystem.UnitTests.csproj
    - name: LeaveSystem - Build
      run: dotnet build --no-restore ./src/LeaveSystem/LeaveSystem.UnitTests/LeaveSystem.UnitTests.csproj
    - name: LeaveSystem - Test
      run: dotnet dotnet test --no-build --verbosity normal ./src/LeaveSystem/LeaveSystem.UnitTests/LeaveSystem.UnitTests.csproj

    - name: LeaveSystem.Api - Restore dependencies
      run: dotnet restore ./src/LeaveSystem.Api/LeaveSystem.Api.UnitTests/LeaveSystem.UnitTests.csproj
    - name: LeaveSystem.Api - Build
      run: dotnet build --no-restore ./src/LeaveSystem.Api/LeaveSystem.Api.UnitTests/LeaveSystem.UnitTests.csproj
    - name: LeaveSystem.Api - Test
      run: dotnet dotnet test --no-build --verbosity normal ./src/LeaveSystem.Api/LeaveSystem.Api.UnitTests/LeaveSystem.UnitTests.csproj

    - name: LeaveSystem.Web - Restore dependencies
      run: dotnet restore ./src/LeaveSystem.Web/LeaveSystem.Web.UnitTests/LeaveSystem.UnitTests.csproj
    - name: LeaveSystem.Web - Build
      run: dotnet build --no-restore ./src/LeaveSystem.Web/LeaveSystem.Web.UnitTests/LeaveSystem.UnitTests.csproj
    - name: LeaveSystem.Web - Test
      run: dotnet dotnet test --no-build --verbosity normal ./src/LeaveSystem.Web/LeaveSystem.Web.UnitTests/LeaveSystem.UnitTests.csproj
